import type {
	GalleryCategory,
	GalleryEntry,
} from "#/features/dev-gallery/lib/types";
import { GALLERY_CATEGORIES } from "#/features/dev-gallery/lib/types";
import {
	AccordionDemo,
	AlertDemo,
	AlertDialogDemo,
	AvatarDemo,
	BadgeDemo,
	BreadcrumbDemo,
	ButtonDemo,
	CardDemo,
	CheckboxDemo,
	CollapsibleDemo,
	DialogDemo,
	DropdownMenuDemo,
	EditorPlaceholder,
	InputDemo,
	LmsCompositesPlaceholder,
	PopoverDemo,
	ProgressDemo,
	RadioGroupDemo,
	SelectDemo,
	SeparatorDemo,
	SheetDemo,
	SkeletonDemo,
	SwitchDemo,
	TableDemo,
	TabsDemo,
	TextareaDemo,
	ToastDemo,
	TooltipDemo,
} from "#/features/dev-gallery/ui/demos";

export const galleryRegistry: GalleryEntry[] = [
	{
		slug: "button",
		title: "Button",
		description: "Primary actions and variants.",
		category: "Foundations",
		component: ButtonDemo,
		note: "import { Button } from '@/components/ui/button'",
	},
	{
		slug: "badge",
		title: "Badge",
		description: "Compact status and labels.",
		category: "Foundations",
		component: BadgeDemo,
		note: "import { Badge } from '@/components/ui/badge'",
	},
	{
		slug: "card",
		title: "Card",
		description: "Grouped content surface.",
		category: "Foundations",
		component: CardDemo,
		note: "import { Card, … } from '@/components/ui/card'",
	},
	{
		slug: "separator",
		title: "Separator",
		description: "Visual divider between sections.",
		category: "Foundations",
		component: SeparatorDemo,
	},
	{
		slug: "skeleton",
		title: "Skeleton",
		description: "Loading placeholders.",
		category: "Foundations",
		component: SkeletonDemo,
	},
	{
		slug: "avatar",
		title: "Avatar",
		description: "User image with fallback initials.",
		category: "Foundations",
		component: AvatarDemo,
	},
	{
		slug: "input",
		title: "Input",
		description: "Single-line text field.",
		category: "Forms",
		component: InputDemo,
		note: "import { Input } from '@/components/ui/input'",
	},
	{
		slug: "textarea",
		title: "Textarea",
		description: "Multi-line text field.",
		category: "Forms",
		component: TextareaDemo,
	},
	{
		slug: "checkbox",
		title: "Checkbox",
		description: "Boolean selection control.",
		category: "Forms",
		component: CheckboxDemo,
	},
	{
		slug: "switch",
		title: "Switch",
		description: "On/off toggle.",
		category: "Forms",
		component: SwitchDemo,
	},
	{
		slug: "select",
		title: "Select",
		description: "Single-choice dropdown.",
		category: "Forms",
		component: SelectDemo,
	},
	{
		slug: "radio-group",
		title: "Radio Group",
		description: "Exclusive option set.",
		category: "Forms",
		component: RadioGroupDemo,
	},
	{
		slug: "alert",
		title: "Alert",
		description: "Inline feedback messages.",
		category: "Feedback",
		component: AlertDemo,
	},
	{
		slug: "dialog",
		title: "Dialog",
		description: "Modal overlay for focused tasks.",
		category: "Feedback",
		component: DialogDemo,
	},
	{
		slug: "alert-dialog",
		title: "Alert Dialog",
		description: "Destructive confirmation modal.",
		category: "Feedback",
		component: AlertDialogDemo,
	},
	{
		slug: "progress",
		title: "Progress",
		description: "Determinate progress bar.",
		category: "Feedback",
		component: ProgressDemo,
	},
	{
		slug: "toast",
		title: "Toast",
		description: "Transient notifications via Sonner.",
		category: "Feedback",
		component: ToastDemo,
		note: "import { toast } from 'sonner'",
	},
	{
		slug: "tabs",
		title: "Tabs",
		description: "Sectioned content panels.",
		category: "Navigation",
		component: TabsDemo,
	},
	{
		slug: "accordion",
		title: "Accordion",
		description: "Expandable content sections.",
		category: "Navigation",
		component: AccordionDemo,
	},
	{
		slug: "breadcrumb",
		title: "Breadcrumb",
		description: "Hierarchical location trail.",
		category: "Navigation",
		component: BreadcrumbDemo,
	},
	{
		slug: "collapsible",
		title: "Collapsible",
		description: "Show/hide a content block.",
		category: "Navigation",
		component: CollapsibleDemo,
	},
	{
		slug: "sheet",
		title: "Sheet",
		description: "Side panel overlay.",
		category: "Navigation",
		component: SheetDemo,
	},
	{
		slug: "dropdown-menu",
		title: "Dropdown Menu",
		description: "Action menu anchored to a trigger.",
		category: "Navigation",
		component: DropdownMenuDemo,
	},
	{
		slug: "tooltip",
		title: "Tooltip",
		description: "Hover hint for a control.",
		category: "Navigation",
		component: TooltipDemo,
	},
	{
		slug: "popover",
		title: "Popover",
		description: "Anchored rich content panel.",
		category: "Navigation",
		component: PopoverDemo,
	},
	{
		slug: "table",
		title: "Table",
		description: "Tabular data display.",
		category: "Data display",
		component: TableDemo,
		note: "import { Table, … } from '@/components/ui/table'",
	},
	{
		slug: "lms-composites",
		title: "LMS composites",
		description: "Product composites (page header, empty state, …).",
		category: "LMS composites",
		component: LmsCompositesPlaceholder,
		note: "Registered in Task 7.",
	},
	{
		slug: "editor",
		title: "Editor",
		description: "TipTap theory/practice editor demos.",
		category: "Editor",
		component: EditorPlaceholder,
		note: "Registered with TipTap work later.",
	},
];

export function getGalleryEntry(slug: string): GalleryEntry | undefined {
	return galleryRegistry.find((entry) => entry.slug === slug);
}

export function getEntriesByCategory(): Array<{
	category: GalleryCategory;
	entries: GalleryEntry[];
}> {
	return GALLERY_CATEGORIES.map((category) => ({
		category,
		entries: galleryRegistry.filter((entry) => entry.category === category),
	})).filter((group) => group.entries.length > 0);
}
