import type {
	GalleryCategory,
	GalleryEntry,
} from "#/features/dev-gallery/lib/types";
import { GALLERY_CATEGORIES } from "#/features/dev-gallery/lib/types";
import {
	AccordionDemo,
	AlertDemo,
	AlertDialogDemo,
	AvatarDemo,
	BadgeDemo,
	BreadcrumbDemo,
	ButtonDemo,
	CardDemo,
	CheckboxDemo,
	CollapsibleDemo,
	DialogDemo,
	DropdownMenuDemo,
	InputDemo,
	PopoverDemo,
	ProgressDemo,
	RadioGroupDemo,
	SelectDemo,
	SeparatorDemo,
	SheetDemo,
	SkeletonDemo,
	SwitchDemo,
	TableDemo,
	TabsDemo,
	TextareaDemo,
	ToastDemo,
	TooltipDemo,
} from "#/features/dev-gallery/ui/demos";
import { TheoryEditorDemo } from "#/features/dev-gallery/ui/editor-demos";
import {
	FileUploadAnswerDemo,
	FormInviteCreateDemo,
	FormLoginPatternDemo,
	MultipleChoiceAnswerDemo,
	ShortTextAnswerDemo,
	SingleChoiceAnswerDemo,
} from "#/features/dev-gallery/ui/form-demos";
import {
	ConfirmActionDialogDemo,
	ContinueLearningCardDemo,
	EmptyStateDemo,
	EntityRowDemo,
	FileDropzoneDemo,
	PageHeaderDemo,
	PendingReviewListDemo,
	ProgramCardDemo,
	ProgressStatDemo,
	PublishToggleDemo,
	StatCardDemo,
	StatusBadgeDemo,
	SupportMessageBubbleDemo,
	TopicTimelineDemo,
	VideoEmbedFrameDemo,
} from "#/features/dev-gallery/ui/lms-demos";

export const galleryRegistry: GalleryEntry[] = [
	{
		slug: "button",
		title: "Button",
		description: "Primary actions and variants.",
		category: "Foundations",
		component: ButtonDemo,
		note: "import { Button } from '@/components/ui/button'",
	},
	{
		slug: "badge",
		title: "Badge",
		description: "Compact status and labels.",
		category: "Foundations",
		component: BadgeDemo,
		note: "import { Badge } from '@/components/ui/badge'",
	},
	{
		slug: "card",
		title: "Card",
		description: "Grouped content surface.",
		category: "Foundations",
		component: CardDemo,
		note: "import { Card, … } from '@/components/ui/card'",
	},
	{
		slug: "separator",
		title: "Separator",
		description: "Visual divider between sections.",
		category: "Foundations",
		component: SeparatorDemo,
	},
	{
		slug: "skeleton",
		title: "Skeleton",
		description: "Loading placeholders.",
		category: "Foundations",
		component: SkeletonDemo,
	},
	{
		slug: "avatar",
		title: "Avatar",
		description: "User image with fallback initials.",
		category: "Foundations",
		component: AvatarDemo,
	},
	{
		slug: "input",
		title: "Input",
		description: "Single-line text field.",
		category: "Forms",
		component: InputDemo,
		note: "import { Input } from '@/components/ui/input'",
	},
	{
		slug: "textarea",
		title: "Textarea",
		description: "Multi-line text field.",
		category: "Forms",
		component: TextareaDemo,
	},
	{
		slug: "checkbox",
		title: "Checkbox",
		description: "Boolean selection control.",
		category: "Forms",
		component: CheckboxDemo,
	},
	{
		slug: "switch",
		title: "Switch",
		description: "On/off toggle.",
		category: "Forms",
		component: SwitchDemo,
	},
	{
		slug: "select",
		title: "Select",
		description: "Single-choice dropdown.",
		category: "Forms",
		component: SelectDemo,
	},
	{
		slug: "radio-group",
		title: "Radio Group",
		description: "Exclusive option set.",
		category: "Forms",
		component: RadioGroupDemo,
	},
	{
		slug: "form-login-pattern",
		title: "Login Form Pattern",
		description: "Email/password layout with client-side validation states.",
		category: "Forms",
		component: FormLoginPatternDemo,
		note: "Presentational demo — not wired to Better Auth.",
	},
	{
		slug: "form-invite-create",
		title: "Invite Create Form",
		description: "Title, email, and multi-select of programs.",
		category: "Forms",
		component: FormInviteCreateDemo,
		note: "Uses Checkbox list for program multi-select.",
	},
	{
		slug: "short-text-answer",
		title: "Short Text Answer",
		description: "Practice short-text widget with error and disabled states.",
		category: "Forms",
		component: ShortTextAnswerDemo,
		note: "import { ShortTextAnswer } from '@/components/answer-widgets'",
	},
	{
		slug: "single-choice-answer",
		title: "Single Choice Answer",
		description:
			"Practice single-choice widget with error and disabled states.",
		category: "Forms",
		component: SingleChoiceAnswerDemo,
		note: "import { SingleChoiceAnswer } from '@/components/answer-widgets'",
	},
	{
		slug: "multiple-choice-answer",
		title: "Multiple Choice Answer",
		description: "Practice multi-choice widget with error and disabled states.",
		category: "Forms",
		component: MultipleChoiceAnswerDemo,
		note: "import { MultipleChoiceAnswer } from '@/components/answer-widgets'",
	},
	{
		slug: "file-upload-answer",
		title: "File Upload Answer",
		description:
			"Multi-file answer with per-file preview/progress; submit gated until all uploads finish.",
		category: "Forms",
		component: FileUploadAnswerDemo,
		note: "import { FileUploadAnswer, simulateUpload } from '@/components/answer-widgets'",
	},
	{
		slug: "alert",
		title: "Alert",
		description: "Inline feedback messages.",
		category: "Feedback",
		component: AlertDemo,
	},
	{
		slug: "dialog",
		title: "Dialog",
		description: "Modal overlay for focused tasks.",
		category: "Feedback",
		component: DialogDemo,
	},
	{
		slug: "alert-dialog",
		title: "Alert Dialog",
		description: "Destructive confirmation modal.",
		category: "Feedback",
		component: AlertDialogDemo,
	},
	{
		slug: "progress",
		title: "Progress",
		description: "Determinate progress bar.",
		category: "Feedback",
		component: ProgressDemo,
	},
	{
		slug: "toast",
		title: "Toast",
		description: "Transient notifications via Sonner.",
		category: "Feedback",
		component: ToastDemo,
		note: "import { toast } from 'sonner'",
	},
	{
		slug: "tabs",
		title: "Tabs",
		description: "Sectioned content panels.",
		category: "Navigation",
		component: TabsDemo,
	},
	{
		slug: "accordion",
		title: "Accordion",
		description: "Expandable content sections.",
		category: "Navigation",
		component: AccordionDemo,
	},
	{
		slug: "breadcrumb",
		title: "Breadcrumb",
		description: "Hierarchical location trail.",
		category: "Navigation",
		component: BreadcrumbDemo,
	},
	{
		slug: "collapsible",
		title: "Collapsible",
		description: "Show/hide a content block.",
		category: "Navigation",
		component: CollapsibleDemo,
	},
	{
		slug: "sheet",
		title: "Sheet",
		description: "Side panel overlay.",
		category: "Navigation",
		component: SheetDemo,
	},
	{
		slug: "dropdown-menu",
		title: "Dropdown Menu",
		description: "Action menu anchored to a trigger.",
		category: "Navigation",
		component: DropdownMenuDemo,
	},
	{
		slug: "tooltip",
		title: "Tooltip",
		description: "Hover hint for a control.",
		category: "Navigation",
		component: TooltipDemo,
	},
	{
		slug: "popover",
		title: "Popover",
		description: "Anchored rich content panel.",
		category: "Navigation",
		component: PopoverDemo,
	},
	{
		slug: "table",
		title: "Table",
		description: "Tabular data display.",
		category: "Data display",
		component: TableDemo,
		note: "import { Table, … } from '@/components/ui/table'",
	},
	{
		slug: "page-header",
		title: "Page Header",
		description:
			"Title, description, and page actions for admin/student screens.",
		category: "LMS composites",
		component: PageHeaderDemo,
		note: "import { PageHeader } from '@/components/lms'",
	},
	{
		slug: "empty-state",
		title: "Empty State",
		description: "Placeholder for empty lists and catalogs.",
		category: "LMS composites",
		component: EmptyStateDemo,
		note: "import { EmptyState } from '@/components/lms'",
	},
	{
		slug: "stat-card",
		title: "Stat Card",
		description: "Compact metric tile for student home infographics.",
		category: "LMS composites",
		component: StatCardDemo,
		note: "import { StatCard } from '@/components/lms'",
	},
	{
		slug: "progress-stat",
		title: "Progress Stat",
		description: "Labeled progress bar for programs and lessons.",
		category: "LMS composites",
		component: ProgressStatDemo,
		note: "import { ProgressStat } from '@/components/lms'",
	},
	{
		slug: "topic-timeline",
		title: "Topic Timeline",
		description: "Vertical topic progress rings connected by a line.",
		category: "LMS composites",
		component: TopicTimelineDemo,
		note: "import { TopicTimeline } from '@/components/lms'",
	},
	{
		slug: "status-badge",
		title: "Status Badge",
		description: "Draft/published and pending/graded status chips.",
		category: "LMS composites",
		component: StatusBadgeDemo,
		note: "import { StatusBadge } from '@/components/lms'",
	},
	{
		slug: "program-card",
		title: "Program Card",
		description: "Program summary with optional progress for student lists.",
		category: "LMS composites",
		component: ProgramCardDemo,
		note: "import { ProgramCard } from '@/components/lms'",
	},
	{
		slug: "continue-learning-card",
		title: "Continue Learning Card",
		description: "Home CTA to resume the current lesson.",
		category: "LMS composites",
		component: ContinueLearningCardDemo,
		note: "import { ContinueLearningCard } from '@/components/lms'",
	},
	{
		slug: "pending-review-list",
		title: "Pending Review List",
		description: "Teaser list of submissions awaiting manual review.",
		category: "LMS composites",
		component: PendingReviewListDemo,
		note: "import { PendingReviewList } from '@/components/lms'",
	},
	{
		slug: "file-dropzone",
		title: "File Dropzone",
		description: "Drag-and-drop file picker for practice uploads.",
		category: "LMS composites",
		component: FileDropzoneDemo,
		note: "import { FileDropzone } from '@/components/lms' — onFiles(File[]) / onFile(File), optional multiple.",
	},
	{
		slug: "publish-toggle",
		title: "Publish Toggle",
		description: "Draft vs published switch for admin CMS.",
		category: "LMS composites",
		component: PublishToggleDemo,
		note: "import { PublishToggle } from '@/components/lms'",
	},
	{
		slug: "entity-row",
		title: "Entity Row",
		description: "Sortable admin list row with status and actions.",
		category: "LMS composites",
		component: EntityRowDemo,
		note: "import { EntityRow } from '@/components/lms'",
	},
	{
		slug: "support-message-bubble",
		title: "Support Message Bubble",
		description: "Chat bubble for student ↔ teacher support thread.",
		category: "LMS composites",
		component: SupportMessageBubbleDemo,
		note: "import { SupportMessageBubble } from '@/components/lms'",
	},
	{
		slug: "video-embed-frame",
		title: "Video Embed Frame",
		description: "Sandboxed iframe wrapper for theory video embeds.",
		category: "LMS composites",
		component: VideoEmbedFrameDemo,
		note: "import { VideoEmbedFrame } from '@/components/lms'",
	},
	{
		slug: "confirm-action-dialog",
		title: "Confirm Action Dialog",
		description: "AlertDialog wrapper for destructive admin actions.",
		category: "LMS composites",
		component: ConfirmActionDialogDemo,
		note: "import { ConfirmActionDialog } from '@/components/lms'",
	},
	{
		slug: "theory-editor",
		title: "Theory Editor",
		description:
			"TipTap StarterKit + video + liveReact/Mafs; editor and read-only renderer. Scope: React, Mafs, Coordinates, Plot, Theme, …",
		category: "Editor",
		component: TheoryEditorDemo,
		note: "import { TheoryEditor, TheoryRenderer, LiveReactBlock } from '#/features/lesson-editor'",
	},
];

export function getGalleryEntry(slug: string): GalleryEntry | undefined {
	return galleryRegistry.find((entry) => entry.slug === slug);
}

export function getEntriesByCategory(): Array<{
	category: GalleryCategory;
	entries: GalleryEntry[];
}> {
	return GALLERY_CATEGORIES.map((category) => ({
		category,
		entries: galleryRegistry.filter((entry) => entry.category === category),
	})).filter((group) => group.entries.length > 0);
}
