// @generated drizzle-zero signature:sha256:048a286379dbc725ec7b8978b14bfc71f7655645ee6bfde0da4d77cc308c5a30
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const chatTable = {
    "name": "chat",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdBy": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const messageTable = {
    "name": "message",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "chatId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "authorId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "content": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "login": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"],
    "serverName": "users"
} as const;
const userRelationships = {
    "chats": [{ "sourceField": ["id"], "destField": ["createdBy"], "destSchema": "chat", "cardinality": "many" }],
    "messages": [{ "sourceField": ["id"], "destField": ["authorId"], "destSchema": "message", "cardinality": "many" }]
} as const;
const chatRelationships = {
    "creator": [{ "sourceField": ["createdBy"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "messages": [{ "sourceField": ["id"], "destField": ["chatId"], "destSchema": "message", "cardinality": "many" }]
} as const;
const messageRelationships = {
    "chat": [{ "sourceField": ["chatId"], "destField": ["id"], "destSchema": "chat", "cardinality": "one" }],
    "author": [{ "sourceField": ["authorId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "chat": chatTable,
        "message": messageTable,
        "user": userTable
    },
    "relationships": {
        "user": userRelationships,
        "chat": chatRelationships,
        "message": messageRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "chat" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Chat = Row<(typeof schema)["tables"]["chat"]>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<(typeof schema)["tables"]["message"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
