#!/usr/bin/env bun
/**
 * drizzle-zero often emits `customType: null as unknown as unknown`.
 * Rewrite those to the column's primitive `type` so app code stays typed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const schemaPath = resolve("src/server/zero/schema.ts");
let source = readFileSync(schemaPath, "utf8");

const patched = source.replace(
	/type:\s*"(string|number|boolean)"([\s\S]*?)customType:\s*null as unknown as unknown/g,
	(_match, primitive: string, middle: string) =>
		`type: "${primitive}"${middle}customType: null as unknown as ${primitive}`,
);

if (patched === source) {
	console.log("fix-zero-schema: no unknown customType entries to patch");
} else {
	const header =
		"// @generated drizzle-zero signature:sha256:manual-primitives-after-fix\n" +
		"// This file was automatically generated by drizzle-zero, then patched by scripts/fix-zero-schema.ts.\n" +
		"// Prefer primitive customType (string / number / boolean). Re-run `bun run zero:generate` after schema changes.\n\n";

	const withoutOldHeader = patched.replace(/^\/\/[^\n]*\n(?:\/\/[^\n]*\n)*/m, "");
	writeFileSync(schemaPath, header + withoutOldHeader);
	console.log("fix-zero-schema: patched primitive customType entries");
}
