// @generated drizzle-zero signature:sha256:41889f8c50db445c21cb026e301b8c936701908658a0a1a8394bf6bd8c1da14c
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const userTable = {
	name: "user",
	columns: {
		id: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		name: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		email: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		emailVerified: {
			type: "boolean",
			optional: true,
			customType: null as unknown as boolean,
			serverName: "email_verified",
		},
		image: {
			type: "string",
			optional: true,
			customType: null as unknown as string,
		},
		role: {
			type: "string",
			optional: true,
			customType: null as unknown as string,
		},
		createdAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
			serverName: "created_at",
		},
		updatedAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
			serverName: "updated_at",
		},
	},
	primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
	tables: {
		user: userTable,
	},
	relationships: {},
	enableLegacyQueries: false,
	enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
	interface DefaultTypes {
		schema: Schema;
	}
}
