// @generated drizzle-zero signature:sha256:23f9b0edbd1608ad6fff6ed3b69a177da43913afd2906146eb515dda9fb99e6d
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema";

export type ActivityContentCustomType = CustomType<typeof drizzleSchema, "activity", "content">;
export type TestPromptCustomType = CustomType<typeof drizzleSchema, "test", "prompt">;
export type TestOptionsCustomType = CustomType<typeof drizzleSchema, "test", "options">;
export type TestAttemptAnswerAnswerCustomType = CustomType<typeof drizzleSchema, "testAttemptAnswer", "answer">;
export type TestKeyCorrectAnswerCustomType = CustomType<typeof drizzleSchema, "testKey", "correctAnswer">;

const activityTable = {
    "name": "activity",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "lessonId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "lesson_id"
        },
        "type": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "position": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "content": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ActivityContentCustomType
        }
    },
    "primaryKey": ["id"]
} as const;
const activityProgressTable = {
    "name": "activityProgress",
    "columns": {
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "activityId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "activity_id"
        },
        "status": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "videoPositionSec": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "video_position_sec"
        },
        "videoPercent": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "video_percent"
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        }
    },
    "primaryKey": ["userId", "programId", "activityId"],
    "serverName": "activity_progress"
} as const;
const enrollmentTable = {
    "name": "enrollment",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const lessonTable = {
    "name": "lesson",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "homeProgramId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "home_program_id"
        },
        "homeTopicId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "home_topic_id"
        }
    },
    "primaryKey": ["id"]
} as const;
const lessonLockEdgeTable = {
    "name": "lessonLockEdge",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "topicId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "topic_id"
        },
        "blockerLessonId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "blocker_lesson_id"
        },
        "lessonId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "lesson_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "lesson_lock_edge"
} as const;
const lessonProgressTable = {
    "name": "lessonProgress",
    "columns": {
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "lessonId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "lesson_id"
        },
        "status": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "percent": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        }
    },
    "primaryKey": ["userId", "programId", "lessonId"],
    "serverName": "lesson_progress"
} as const;
const programTable = {
    "name": "program",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "description": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "examType": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "exam_type"
        },
        "subject": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "public": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "topicLockMode": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "topic_lock_mode"
        },
        "lessonLockMode": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "lesson_lock_mode"
        },
        "unlockThresholdPercent": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "unlock_threshold_percent"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const programInviteTable = {
    "name": "programInvite",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "token": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdByUserId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "created_by_user_id"
        },
        "inviteeEmail": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "invitee_email"
        },
        "inviteeName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "invitee_name"
        },
        "expiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "usedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "used_at"
        },
        "usedByUserId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "used_by_user_id"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "program_invite"
} as const;
const programInviteProgramTable = {
    "name": "programInviteProgram",
    "columns": {
        "inviteId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "invite_id"
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        }
    },
    "primaryKey": ["inviteId", "programId"],
    "serverName": "program_invite_program"
} as const;
const supportMessageTable = {
    "name": "supportMessage",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "threadId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "thread_id"
        },
        "authorId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "author_id"
        },
        "body": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "support_message"
} as const;
const supportThreadTable = {
    "name": "supportThread",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "studentUserId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "student_user_id"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "support_thread"
} as const;
const testTable = {
    "name": "test",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "groupId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "group_id"
        },
        "position": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "prompt": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as TestPromptCustomType
        },
        "answerType": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "answer_type"
        },
        "options": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as TestOptionsCustomType
        },
        "grading": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const testAttemptTable = {
    "name": "testAttempt",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "activityId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "activity_id"
        },
        "testIds": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as string[],
            "serverName": "test_ids"
        },
        "status": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "scorePercent": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "score_percent"
        },
        "passed": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "test_attempt"
} as const;
const testAttemptAnswerTable = {
    "name": "testAttemptAnswer",
    "columns": {
        "attemptId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "attempt_id"
        },
        "testId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "test_id"
        },
        "answer": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as TestAttemptAnswerAnswerCustomType
        },
        "result": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "reviewedBy": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "reviewed_by"
        },
        "reviewerComment": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "reviewer_comment"
        },
        "reviewedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "reviewed_at"
        }
    },
    "primaryKey": ["attemptId", "testId"],
    "serverName": "test_attempt_answer"
} as const;
const testGroupTable = {
    "name": "testGroup",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "description": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"],
    "serverName": "test_group"
} as const;
const testKeyTable = {
    "name": "testKey",
    "columns": {
        "testId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "test_id"
        },
        "correctAnswer": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as TestKeyCorrectAnswerCustomType,
            "serverName": "correct_answer"
        }
    },
    "primaryKey": ["testId"],
    "serverName": "test_key"
} as const;
const topicTable = {
    "name": "topic",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "position": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const topicLessonTable = {
    "name": "topicLesson",
    "columns": {
        "topicId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "topic_id"
        },
        "lessonId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "lesson_id"
        },
        "position": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        }
    },
    "primaryKey": ["topicId", "lessonId"],
    "serverName": "topic_lesson"
} as const;
const topicLockEdgeTable = {
    "name": "topicLockEdge",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "programId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "program_id"
        },
        "blockerTopicId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "blocker_topic_id"
        },
        "topicId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "topic_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "topic_lock_edge"
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "email": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "emailVerified": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "email_verified"
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "username": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "displayUsername": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "display_username"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "notifySupportReply": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "notify_support_reply"
        },
        "notifyReviewGraded": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "notify_review_graded"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const userRelationships = {
    "enrollments": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "enrollment", "cardinality": "many" }],
    "supportThreads": [{ "sourceField": ["id"], "destField": ["studentUserId"], "destSchema": "supportThread", "cardinality": "many" }],
    "supportMessages": [{ "sourceField": ["id"], "destField": ["authorId"], "destSchema": "supportMessage", "cardinality": "many" }],
    "testAttempts": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "testAttempt", "cardinality": "many" }]
} as const;
const programRelationships = {
    "topics": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "topic", "cardinality": "many" }],
    "testAttempts": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "testAttempt", "cardinality": "many" }],
    "activityProgress": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "activityProgress", "cardinality": "many" }],
    "lessonProgress": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "lessonProgress", "cardinality": "many" }],
    "enrollments": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "enrollment", "cardinality": "many" }],
    "invitePrograms": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "programInviteProgram", "cardinality": "many" }],
    "topicLockEdges": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "topicLockEdge", "cardinality": "many" }],
    "lessonLockEdges": [{ "sourceField": ["id"], "destField": ["programId"], "destSchema": "lessonLockEdge", "cardinality": "many" }]
} as const;
const topicRelationships = {
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "topicLessons": [{ "sourceField": ["id"], "destField": ["topicId"], "destSchema": "topicLesson", "cardinality": "many" }]
} as const;
const lessonRelationships = {
    "topicLessons": [{ "sourceField": ["id"], "destField": ["lessonId"], "destSchema": "topicLesson", "cardinality": "many" }],
    "activities": [{ "sourceField": ["id"], "destField": ["lessonId"], "destSchema": "activity", "cardinality": "many" }],
    "lessonProgress": [{ "sourceField": ["id"], "destField": ["lessonId"], "destSchema": "lessonProgress", "cardinality": "many" }],
    "homeProgram": [{ "sourceField": ["homeProgramId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "homeTopic": [{ "sourceField": ["homeTopicId"], "destField": ["id"], "destSchema": "topic", "cardinality": "one" }]
} as const;
const topicLessonRelationships = {
    "topic": [{ "sourceField": ["topicId"], "destField": ["id"], "destSchema": "topic", "cardinality": "one" }],
    "lesson": [{ "sourceField": ["lessonId"], "destField": ["id"], "destSchema": "lesson", "cardinality": "one" }]
} as const;
const topicLockEdgeRelationships = {
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "blockerTopic": [{ "sourceField": ["blockerTopicId"], "destField": ["id"], "destSchema": "topic", "cardinality": "one" }],
    "topic": [{ "sourceField": ["topicId"], "destField": ["id"], "destSchema": "topic", "cardinality": "one" }]
} as const;
const lessonLockEdgeRelationships = {
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "topic": [{ "sourceField": ["topicId"], "destField": ["id"], "destSchema": "topic", "cardinality": "one" }],
    "blockerLesson": [{ "sourceField": ["blockerLessonId"], "destField": ["id"], "destSchema": "lesson", "cardinality": "one" }],
    "lesson": [{ "sourceField": ["lessonId"], "destField": ["id"], "destSchema": "lesson", "cardinality": "one" }]
} as const;
const activityRelationships = {
    "lesson": [{ "sourceField": ["lessonId"], "destField": ["id"], "destSchema": "lesson", "cardinality": "one" }],
    "testAttempts": [{ "sourceField": ["id"], "destField": ["activityId"], "destSchema": "testAttempt", "cardinality": "many" }],
    "activityProgress": [{ "sourceField": ["id"], "destField": ["activityId"], "destSchema": "activityProgress", "cardinality": "many" }]
} as const;
const testGroupRelationships = {
    "tests": [{ "sourceField": ["id"], "destField": ["groupId"], "destSchema": "test", "cardinality": "many" }]
} as const;
const testRelationships = {
    "group": [{ "sourceField": ["groupId"], "destField": ["id"], "destSchema": "testGroup", "cardinality": "one" }],
    "key": [{ "sourceField": ["id"], "destField": ["testId"], "destSchema": "testKey", "cardinality": "one" }],
    "attemptAnswers": [{ "sourceField": ["id"], "destField": ["testId"], "destSchema": "testAttemptAnswer", "cardinality": "many" }]
} as const;
const testKeyRelationships = {
    "test": [{ "sourceField": ["testId"], "destField": ["id"], "destSchema": "test", "cardinality": "one" }]
} as const;
const testAttemptRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "activity": [{ "sourceField": ["activityId"], "destField": ["id"], "destSchema": "activity", "cardinality": "one" }],
    "answers": [{ "sourceField": ["id"], "destField": ["attemptId"], "destSchema": "testAttemptAnswer", "cardinality": "many" }]
} as const;
const testAttemptAnswerRelationships = {
    "attempt": [{ "sourceField": ["attemptId"], "destField": ["id"], "destSchema": "testAttempt", "cardinality": "one" }],
    "test": [{ "sourceField": ["testId"], "destField": ["id"], "destSchema": "test", "cardinality": "one" }],
    "reviewer": [{ "sourceField": ["reviewedBy"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const activityProgressRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "activity": [{ "sourceField": ["activityId"], "destField": ["id"], "destSchema": "activity", "cardinality": "one" }]
} as const;
const lessonProgressRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }],
    "lesson": [{ "sourceField": ["lessonId"], "destField": ["id"], "destSchema": "lesson", "cardinality": "one" }]
} as const;
const programInviteRelationships = {
    "createdBy": [{ "sourceField": ["createdByUserId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "usedBy": [{ "sourceField": ["usedByUserId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "programs": [{ "sourceField": ["id"], "destField": ["inviteId"], "destSchema": "programInviteProgram", "cardinality": "many" }]
} as const;
const programInviteProgramRelationships = {
    "invite": [{ "sourceField": ["inviteId"], "destField": ["id"], "destSchema": "programInvite", "cardinality": "one" }],
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }]
} as const;
const enrollmentRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "program": [{ "sourceField": ["programId"], "destField": ["id"], "destSchema": "program", "cardinality": "one" }]
} as const;
const supportThreadRelationships = {
    "student": [{ "sourceField": ["studentUserId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "messages": [{ "sourceField": ["id"], "destField": ["threadId"], "destSchema": "supportMessage", "cardinality": "many" }]
} as const;
const supportMessageRelationships = {
    "thread": [{ "sourceField": ["threadId"], "destField": ["id"], "destSchema": "supportThread", "cardinality": "one" }],
    "author": [{ "sourceField": ["authorId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "activity": activityTable,
        "activityProgress": activityProgressTable,
        "enrollment": enrollmentTable,
        "lesson": lessonTable,
        "lessonLockEdge": lessonLockEdgeTable,
        "lessonProgress": lessonProgressTable,
        "program": programTable,
        "programInvite": programInviteTable,
        "programInviteProgram": programInviteProgramTable,
        "supportMessage": supportMessageTable,
        "supportThread": supportThreadTable,
        "test": testTable,
        "testAttempt": testAttemptTable,
        "testAttemptAnswer": testAttemptAnswerTable,
        "testGroup": testGroupTable,
        "testKey": testKeyTable,
        "topic": topicTable,
        "topicLesson": topicLessonTable,
        "topicLockEdge": topicLockEdgeTable,
        "user": userTable
    },
    "relationships": {
        "user": userRelationships,
        "program": programRelationships,
        "topic": topicRelationships,
        "lesson": lessonRelationships,
        "topicLesson": topicLessonRelationships,
        "topicLockEdge": topicLockEdgeRelationships,
        "lessonLockEdge": lessonLockEdgeRelationships,
        "activity": activityRelationships,
        "testGroup": testGroupRelationships,
        "test": testRelationships,
        "testKey": testKeyRelationships,
        "testAttempt": testAttemptRelationships,
        "testAttemptAnswer": testAttemptAnswerRelationships,
        "activityProgress": activityProgressRelationships,
        "lessonProgress": lessonProgressRelationships,
        "programInvite": programInviteRelationships,
        "programInviteProgram": programInviteProgramRelationships,
        "enrollment": enrollmentRelationships,
        "supportThread": supportThreadRelationships,
        "supportMessage": supportMessageRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "activity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<(typeof schema)["tables"]["activity"]>;
/**
 * Represents a row from the "activityProgress" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ActivityProgress = Row<(typeof schema)["tables"]["activityProgress"]>;
/**
 * Represents a row from the "enrollment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Enrollment = Row<(typeof schema)["tables"]["enrollment"]>;
/**
 * Represents a row from the "lesson" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Lesson = Row<(typeof schema)["tables"]["lesson"]>;
/**
 * Represents a row from the "lessonLockEdge" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LessonLockEdge = Row<(typeof schema)["tables"]["lessonLockEdge"]>;
/**
 * Represents a row from the "lessonProgress" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LessonProgress = Row<(typeof schema)["tables"]["lessonProgress"]>;
/**
 * Represents a row from the "program" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Program = Row<(typeof schema)["tables"]["program"]>;
/**
 * Represents a row from the "programInvite" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProgramInvite = Row<(typeof schema)["tables"]["programInvite"]>;
/**
 * Represents a row from the "programInviteProgram" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProgramInviteProgram = Row<(typeof schema)["tables"]["programInviteProgram"]>;
/**
 * Represents a row from the "supportMessage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SupportMessage = Row<(typeof schema)["tables"]["supportMessage"]>;
/**
 * Represents a row from the "supportThread" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SupportThread = Row<(typeof schema)["tables"]["supportThread"]>;
/**
 * Represents a row from the "test" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Test = Row<(typeof schema)["tables"]["test"]>;
/**
 * Represents a row from the "testAttempt" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TestAttempt = Row<(typeof schema)["tables"]["testAttempt"]>;
/**
 * Represents a row from the "testAttemptAnswer" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TestAttemptAnswer = Row<(typeof schema)["tables"]["testAttemptAnswer"]>;
/**
 * Represents a row from the "testGroup" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TestGroup = Row<(typeof schema)["tables"]["testGroup"]>;
/**
 * Represents a row from the "testKey" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TestKey = Row<(typeof schema)["tables"]["testKey"]>;
/**
 * Represents a row from the "topic" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Topic = Row<(typeof schema)["tables"]["topic"]>;
/**
 * Represents a row from the "topicLesson" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TopicLesson = Row<(typeof schema)["tables"]["topicLesson"]>;
/**
 * Represents a row from the "topicLockEdge" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TopicLockEdge = Row<(typeof schema)["tables"]["topicLockEdge"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
