// @generated drizzle-zero signature:sha256:manual-primitives-after-better-auth
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Note: customType uses primitives because drizzle-zero CustomType resolved to unknown.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const chatTable = {
	name: "chat",
	columns: {
		id: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		title: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		createdAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
		},
		createdBy: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
	},
	primaryKey: ["id"],
} as const;
const messageTable = {
	name: "message",
	columns: {
		id: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		chatId: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		authorId: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		content: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		createdAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
		},
	},
	primaryKey: ["id"],
} as const;
const userTable = {
	name: "user",
	columns: {
		id: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		name: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		email: {
			type: "string",
			optional: false,
			customType: null as unknown as string,
		},
		emailVerified: {
			type: "boolean",
			optional: true,
			customType: null as unknown as boolean,
			serverName: "email_verified",
		},
		image: {
			type: "string",
			optional: true,
			customType: null as unknown as string,
		},
		createdAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
			serverName: "created_at",
		},
		updatedAt: {
			type: "number",
			optional: true,
			customType: null as unknown as number,
			serverName: "updated_at",
		},
	},
	primaryKey: ["id"],
} as const;
const userRelationships = {
	chats: [
		{
			sourceField: ["id"],
			destField: ["createdBy"],
			destSchema: "chat",
			cardinality: "many",
		},
	],
	messages: [
		{
			sourceField: ["id"],
			destField: ["authorId"],
			destSchema: "message",
			cardinality: "many",
		},
	],
} as const;
const chatRelationships = {
	creator: [
		{
			sourceField: ["createdBy"],
			destField: ["id"],
			destSchema: "user",
			cardinality: "one",
		},
	],
	messages: [
		{
			sourceField: ["id"],
			destField: ["chatId"],
			destSchema: "message",
			cardinality: "many",
		},
	],
} as const;
const messageRelationships = {
	chat: [
		{
			sourceField: ["chatId"],
			destField: ["id"],
			destSchema: "chat",
			cardinality: "one",
		},
	],
	author: [
		{
			sourceField: ["authorId"],
			destField: ["id"],
			destSchema: "user",
			cardinality: "one",
		},
	],
} as const;

export const schema = {
	tables: {
		chat: chatTable,
		message: messageTable,
		user: userTable,
	},
	relationships: {
		user: userRelationships,
		chat: chatRelationships,
		message: messageRelationships,
	},
	enableLegacyQueries: false,
	enableLegacyMutators: false,
} as const;

export type Schema = typeof schema;
export type Chat = Row<(typeof schema)["tables"]["chat"]>;
export type Message = Row<(typeof schema)["tables"]["message"]>;
export type User = Row<(typeof schema)["tables"]["user"]>;

export const zql = createBuilder(schema);
export const builder = zql;

declare module "@rocicorp/zero" {
	interface DefaultTypes {
		schema: Schema;
	}
}
