/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroRouteImport } from './routes/zero'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ZeroSplatRouteImport } from './routes/zero/$'
import { Route as DevSlugRouteImport } from './routes/dev/$slug'
import { Route as ApiZeroRouteImport } from './routes/api/zero'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiMutateRouteImport } from './routes/api/mutate'
import { Route as AdminProgramsIndexRouteImport } from './routes/admin/programs/index'
import { Route as AdminLessonsIndexRouteImport } from './routes/admin/lessons/index'
import { Route as AppProgramsProgramIdRouteImport } from './routes/app/programs/$programId'
import { Route as ApiZeroSplatRouteImport } from './routes/api/zero/$'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProgramsProgramIdRouteImport } from './routes/admin/programs/$programId'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/admin/lessons/$lessonId'
import { Route as AppProgramsProgramIdLessonsLessonIdRouteImport } from './routes/app/programs/$programId/lessons/$lessonId'

const ZeroRoute = ZeroRouteImport.update({
  id: '/zero',
  path: '/zero',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ZeroSplatRoute = ZeroSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ZeroRoute,
} as any)
const DevSlugRoute = DevSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DevRoute,
} as any)
const ApiZeroRoute = ApiZeroRouteImport.update({
  id: '/api/zero',
  path: '/api/zero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMutateRoute = ApiMutateRouteImport.update({
  id: '/api/mutate',
  path: '/api/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsIndexRoute = AdminProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRoute,
} as any)
const AppProgramsProgramIdRoute = AppProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => AppRoute,
} as any)
const ApiZeroSplatRoute = ApiZeroSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiZeroRoute,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsProgramIdRoute = AdminProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AdminRoute,
} as any)
const AppProgramsProgramIdLessonsLessonIdRoute =
  AppProgramsProgramIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AppProgramsProgramIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/zero': typeof ZeroRouteWithChildren
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/zero': typeof ApiZeroRouteWithChildren
  '/dev/$slug': typeof DevSlugRoute
  '/zero/$': typeof ZeroSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dev/': typeof DevIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/zero/$': typeof ApiZeroSplatRoute
  '/app/programs/$programId': typeof AppProgramsProgramIdRouteWithChildren
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/programs/': typeof AdminProgramsIndexRoute
  '/app/programs/$programId/lessons/$lessonId': typeof AppProgramsProgramIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/zero': typeof ZeroRouteWithChildren
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/zero': typeof ApiZeroRouteWithChildren
  '/dev/$slug': typeof DevSlugRoute
  '/zero/$': typeof ZeroSplatRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/dev': typeof DevIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/zero/$': typeof ApiZeroSplatRoute
  '/app/programs/$programId': typeof AppProgramsProgramIdRouteWithChildren
  '/admin/lessons': typeof AdminLessonsIndexRoute
  '/admin/programs': typeof AdminProgramsIndexRoute
  '/app/programs/$programId/lessons/$lessonId': typeof AppProgramsProgramIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/zero': typeof ZeroRouteWithChildren
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/zero': typeof ApiZeroRouteWithChildren
  '/dev/$slug': typeof DevSlugRoute
  '/zero/$': typeof ZeroSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dev/': typeof DevIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/zero/$': typeof ApiZeroSplatRoute
  '/app/programs/$programId': typeof AppProgramsProgramIdRouteWithChildren
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/programs/': typeof AdminProgramsIndexRoute
  '/app/programs/$programId/lessons/$lessonId': typeof AppProgramsProgramIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/dev'
    | '/login'
    | '/zero'
    | '/api/mutate'
    | '/api/query'
    | '/api/upload'
    | '/api/zero'
    | '/dev/$slug'
    | '/zero/$'
    | '/admin/'
    | '/app/'
    | '/dev/'
    | '/admin/lessons/$lessonId'
    | '/admin/programs/$programId'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/zero/$'
    | '/app/programs/$programId'
    | '/admin/lessons/'
    | '/admin/programs/'
    | '/app/programs/$programId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/zero'
    | '/api/mutate'
    | '/api/query'
    | '/api/upload'
    | '/api/zero'
    | '/dev/$slug'
    | '/zero/$'
    | '/admin'
    | '/app'
    | '/dev'
    | '/admin/lessons/$lessonId'
    | '/admin/programs/$programId'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/zero/$'
    | '/app/programs/$programId'
    | '/admin/lessons'
    | '/admin/programs'
    | '/app/programs/$programId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/dev'
    | '/login'
    | '/zero'
    | '/api/mutate'
    | '/api/query'
    | '/api/upload'
    | '/api/zero'
    | '/dev/$slug'
    | '/zero/$'
    | '/admin/'
    | '/app/'
    | '/dev/'
    | '/admin/lessons/$lessonId'
    | '/admin/programs/$programId'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/zero/$'
    | '/app/programs/$programId'
    | '/admin/lessons/'
    | '/admin/programs/'
    | '/app/programs/$programId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  LoginRoute: typeof LoginRoute
  ZeroRoute: typeof ZeroRouteWithChildren
  ApiMutateRoute: typeof ApiMutateRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiZeroRoute: typeof ApiZeroRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero': {
      id: '/zero'
      path: '/zero'
      fullPath: '/zero'
      preLoaderRoute: typeof ZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/zero/$': {
      id: '/zero/$'
      path: '/$'
      fullPath: '/zero/$'
      preLoaderRoute: typeof ZeroSplatRouteImport
      parentRoute: typeof ZeroRoute
    }
    '/dev/$slug': {
      id: '/dev/$slug'
      path: '/$slug'
      fullPath: '/dev/$slug'
      preLoaderRoute: typeof DevSlugRouteImport
      parentRoute: typeof DevRoute
    }
    '/api/zero': {
      id: '/api/zero'
      path: '/api/zero'
      fullPath: '/api/zero'
      preLoaderRoute: typeof ApiZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mutate': {
      id: '/api/mutate'
      path: '/api/mutate'
      fullPath: '/api/mutate'
      preLoaderRoute: typeof ApiMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs/': {
      id: '/admin/programs/'
      path: '/programs'
      fullPath: '/admin/programs/'
      preLoaderRoute: typeof AdminProgramsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/': {
      id: '/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons/'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/programs/$programId': {
      id: '/app/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/app/programs/$programId'
      preLoaderRoute: typeof AppProgramsProgramIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/zero/$': {
      id: '/api/zero/$'
      path: '/$'
      fullPath: '/api/zero/$'
      preLoaderRoute: typeof ApiZeroSplatRouteImport
      parentRoute: typeof ApiZeroRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs/$programId': {
      id: '/admin/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/admin/programs/$programId'
      preLoaderRoute: typeof AdminProgramsProgramIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/$lessonId': {
      id: '/admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/programs/$programId/lessons/$lessonId': {
      id: '/app/programs/$programId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/app/programs/$programId/lessons/$lessonId'
      preLoaderRoute: typeof AppProgramsProgramIdLessonsLessonIdRouteImport
      parentRoute: typeof AppProgramsProgramIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
  AdminProgramsProgramIdRoute: typeof AdminProgramsProgramIdRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
  AdminProgramsIndexRoute: typeof AdminProgramsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
  AdminProgramsProgramIdRoute: AdminProgramsProgramIdRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
  AdminProgramsIndexRoute: AdminProgramsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppProgramsProgramIdRouteChildren {
  AppProgramsProgramIdLessonsLessonIdRoute: typeof AppProgramsProgramIdLessonsLessonIdRoute
}

const AppProgramsProgramIdRouteChildren: AppProgramsProgramIdRouteChildren = {
  AppProgramsProgramIdLessonsLessonIdRoute:
    AppProgramsProgramIdLessonsLessonIdRoute,
}

const AppProgramsProgramIdRouteWithChildren =
  AppProgramsProgramIdRoute._addFileChildren(AppProgramsProgramIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProgramsProgramIdRoute: typeof AppProgramsProgramIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProgramsProgramIdRoute: AppProgramsProgramIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DevRouteChildren {
  DevSlugRoute: typeof DevSlugRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevSlugRoute: DevSlugRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface ZeroRouteChildren {
  ZeroSplatRoute: typeof ZeroSplatRoute
}

const ZeroRouteChildren: ZeroRouteChildren = {
  ZeroSplatRoute: ZeroSplatRoute,
}

const ZeroRouteWithChildren = ZeroRoute._addFileChildren(ZeroRouteChildren)

interface ApiZeroRouteChildren {
  ApiZeroSplatRoute: typeof ApiZeroSplatRoute
}

const ApiZeroRouteChildren: ApiZeroRouteChildren = {
  ApiZeroSplatRoute: ApiZeroSplatRoute,
}

const ApiZeroRouteWithChildren =
  ApiZeroRoute._addFileChildren(ApiZeroRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  LoginRoute: LoginRoute,
  ZeroRoute: ZeroRouteWithChildren,
  ApiMutateRoute: ApiMutateRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiZeroRoute: ApiZeroRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
